# Generated by Django 5.2 on 2025-06-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('electrica', 'Instalación eléctrica'), ('transformador', 'Centro de transformación'), ('pci', 'Protección contra incendios'), ('compresor', 'Compresor'), ('puertas', 'Puertas/portones'), ('vehiculos', 'Flota de vehículos')], max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_mantenimiento', models.BooleanField(default=False)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
