# Generated by Django 5.2 on 2025-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='tipo_combustible',
            field=models.CharField(blank=True, choices=[('gas', 'Gas'), ('gasoil', 'Gasoil')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('electrica', 'Instalación eléctrica'), ('transformador', 'Centro de transformación'), ('pci', 'Protección contra incendios'), ('compresor', 'Compresor'), ('puertas', 'Puertas/portones'), ('vehiculos', 'Flota de vehículos'), ('caldera', 'Caldera'), ('quimicos', 'Almacenamiento de productos químicos'), ('petrolifera', 'Instalación petrolífera / Depósito gasoil'), ('frigorifica', 'Instalación frigorífica'), ('estanterias', 'Estanterías industriales')], max_length=30),
        ),
    ]
