# Generated by Django 5.2 on 2025-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_instalacion_tipo_combustible_alter_instalacion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='requiere_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='tipo_combustible',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='instalacion',
            name='documentacion',
            field=models.FileField(blank=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='nombre',
            field=models.CharField(choices=[('electrica', 'Instalación eléctrica'), ('pci', 'Protección contra incendios'), ('centro_transformacion', 'Centro de transformación'), ('compresor', 'Compresor'), ('puertas', 'Puertas/portones'), ('flota', 'Flota de vehículos'), ('caldera_gas', 'Caldera de gas'), ('caldera_gasoil', 'Caldera de gasoil'), ('almacenamiento_quimicos', 'Almacenamiento de productos químicos'), ('instalaciones_petroliferas', 'Instalaciones petrolíferas/depósito gasoil'), ('instalaciones_frigorificas', 'Instalaciones frigoríficas'), ('estanterias', 'Estanterías industriales')], max_length=100),
        ),
    ]
