# Generated by Django 5.2 on 2025-06-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_instalacion_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacion',
            old_name='fecha_ultimo_mantenimiento',
            new_name='fecha_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='proximo_mantenimiento',
        ),
        migrations.AddField(
            model_name='instalacion',
            name='mantenimiento_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='documentacion/'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='nombre',
            field=models.CharField(choices=[('eléctrica', 'Instalación eléctrica'), ('centro_transformacion', 'Centro de transformación'), ('pci', 'Protección contra incendios'), ('compresor', 'Compresor'), ('puertas', 'Puertas/portones'), ('vehiculos', 'Flota de vehículos'), ('caldera_gas', 'Caldera de gas'), ('caldera_gasoil', 'Caldera de gasoil'), ('almacenamiento_quimicos', 'Almacenamiento de productos químicos'), ('instalacion_petrolifera', 'Instalaciones petrolíferas'), ('frigorificas', 'Instalaciones frigoríficas'), ('estanterias', 'Estanterías industriales')], max_length=50),
        ),
    ]
