# Generated by Django 5.2 on 2025-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_fecha_ultimo_mantenimiento_instalacion_fecha_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='frecuencia_mantenimiento_dias',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
