# Generated by Django 5.2 on 2025-06-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_instalacion_frecuencia_mantenimiento_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('plano_unifilar', 'Plano unifilar'), ('certificado_instalacion', 'Certificado de instalación'), ('contrato_mantenimiento', 'Contrato de mantenimiento'), ('revision_periodica', 'Revisión periódica'), ('manual_fabricante', 'Manual del fabricante'), ('boletin_revision', 'Boletín de revisión'), ('informe_mantenimiento', 'Informe de mantenimiento'), ('protocolo_actuacion', 'Protocolo de actuación'), ('ubicacion_equipos', 'Plano ubicación equipos'), ('libro_mantenimiento', 'Libro de mantenimiento'), ('manual_uso', 'Manual de uso'), ('ficha_tecnica', 'Ficha técnica'), ('certificado_presion', 'Certificado presión'), ('documentacion_presion', 'Documentación recipientes presión'), ('marcado_ce', 'Marcado CE'), ('registro_inspeccion', 'Registro de inspección'), ('plano_instalacion', 'Plano instalación'), ('protocolo_limpieza', 'Protocolo limpieza conductos'), ('itv', 'ITV'), ('registro_revisiones', 'Registro de revisiones'), ('parte_reparacion', 'Partes de reparación')], max_length=50)),
                ('archivo', models.FileField(upload_to='documentacion/')),
                ('descripcion', models.TextField(blank=True)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.instalacion')),
            ],
        ),
    ]
