# Generated by Django 5.2 on 2025-06-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_equipotrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('tareas', models.TextField()),
                ('equipos_trabajo', models.TextField(blank=True)),
                ('epis_necesarios', models.TextField(blank=True)),
                ('productos_quimicos', models.TextField(blank=True)),
                ('manipulacion_cargas', models.BooleanField(default=False)),
                ('trabajos_altura', models.BooleanField(default=False)),
                ('espacios_confinados', models.BooleanField(default=False)),
                ('exposicion_ruido', models.BooleanField(default=False)),
                ('tipo_exposicion', models.CharField(blank=True, max_length=200)),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('uso_pvd', models.BooleanField(default=False)),
                ('riesgos_identificados', models.TextField(blank=True)),
                ('medidas_preventivas', models.TextField(blank=True)),
                ('formacion_requerida', models.TextField(blank=True)),
                ('autorizacion_equipos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('equipos_autorizados', models.ManyToManyField(to='gestion.equipotrabajo')),
            ],
        ),
    ]
