# Generated by Django 5.2 on 2025-06-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_puestotrabajo_autorizacionequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='medidas_preventivas',
        ),
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='riesgos_identificados',
        ),
    ]
