# Generated by Django 5.2 on 2025-06-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar_uso', models.CharField(max_length=200)),
                ('lugar_almacenamiento', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('kg', 'kg'), ('L', 'L'), ('uds', 'uds')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fds', models.FileField(blank=True, null=True, upload_to='productos/fds/')),
            ],
        ),
    ]
