# Generated by Django 5.2 on 2025-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_productoquimico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_plan', models.FileField(upload_to='planes_prevencion/')),
                ('tiene_delegado_prevencion', models.BooleanField(default=False)),
                ('acta_delegado', models.FileField(blank=True, null=True, upload_to='delegados/')),
                ('formacion_delegado', models.FileField(blank=True, null=True, upload_to='delegados/')),
                ('trabajos_altura', models.BooleanField(default=False)),
                ('espacios_confinados', models.BooleanField(default=False)),
                ('atm_explosivas', models.BooleanField(default=False)),
                ('excavaciones', models.BooleanField(default=False)),
                ('tiene_recurso_preventivo', models.BooleanField(default=False)),
                ('nombramiento_recurso', models.FileField(blank=True, null=True, upload_to='recursos_preventivos/')),
                ('formacion_recurso', models.FileField(blank=True, null=True, upload_to='recursos_preventivos/')),
            ],
        ),
    ]
