# Generated by Django 5.2 on 2025-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_empresa_alter_planprevencion_documento_plan_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
    ]
