# Generated by Django 5.2 on 2025-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_perfil_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(max_length=255),
        ),
    ]
