# Generated by Django 5.2 on 2025-06-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_perfil_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosPrevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion_riesgos', models.FileField(blank=True, null=True, upload_to='prevencion/')),
                ('plan_actividad_preventiva', models.FileField(blank=True, null=True, upload_to='prevencion/')),
            ],
        ),
        migrations.CreateModel(
            name='MedidaPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=255)),
                ('plazo', models.DateField()),
                ('responsable', models.CharField(max_length=255)),
                ('coste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en curso', 'En curso'), ('implantada', 'Implantada')], default='pendiente', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='planprevencion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
    ]
