# Generated by Django 5.2 on 2025-06-27 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_documentosprevencion_medidapreventiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosprevencion',
            name='evaluacion_riesgos',
        ),
        migrations.RemoveField(
            model_name='documentosprevencion',
            name='plan_actividad_preventiva',
        ),
        migrations.AddField(
            model_name='documentosprevencion',
            name='documento_evaluacion',
            field=models.FileField(blank=True, null=True, upload_to='prevencion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='documentosprevencion',
            name='documento_planificacion',
            field=models.FileField(blank=True, null=True, upload_to='prevencion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
