# Generated by Django 5.2 on 2025-06-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_remove_documentosprevencion_evaluacion_riesgos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidapreventiva',
            name='coste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medidapreventiva',
            name='plazo',
            field=models.CharField(max_length=255),
        ),
    ]
