# Generated by Django 5.2 on 2025-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_medidapreventiva_coste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('plan_emergencia', models.FileField(blank=True, null=True, upload_to='emergencia/plan/')),
                ('simulacros', models.FileField(blank=True, null=True, upload_to='emergencia/simulacros/')),
                ('consignas', models.FileField(blank=True, null=True, upload_to='emergencia/consignas/')),
                ('documento_designacion', models.FileField(blank=True, help_text='Documento base editable para la designación de equipos.', null=True, upload_to='emergencia/designaciones_modelo/')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JEFE', 'Jefe de Emergencia'), ('INTERVENCION', 'Equipo de Intervención'), ('EVACUACION', 'Equipo de Alarma y Evacuación'), ('PRIMEROS AUXILIOS', 'Equipo de Primeros Auxilios')], max_length=30)),
                ('responsable', models.CharField(max_length=100)),
                ('sustituto', models.CharField(blank=True, max_length=100)),
                ('registro_designacion', models.FileField(blank=True, help_text='Documento firmado por el trabajador', null=True, upload_to='emergencia/designaciones/')),
                ('certificado_formacion', models.FileField(blank=True, help_text='Certificado de formación en emergencias', null=True, upload_to='emergencia/formacion/')),
            ],
        ),
    ]
