# Generated by Django 5.2 on 2025-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_documentoemergencia_equipoemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('seleccionado', models.BooleanField(default=False)),
            ],
        ),
    ]
