# Generated by Django 5.2 on 2025-06-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_medioproteccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentoEmergencia',
            new_name='DocumentosEmergencia',
        ),
    ]
