# Generated by Django 5.2 on 2025-06-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_remove_documentosemergencia_consignas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medioproteccion',
            name='seleccionado',
        ),
        migrations.CreateModel(
            name='EmpresaMedioProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
                ('medios', models.ManyToManyField(to='gestion.medioproteccion')),
            ],
        ),
    ]
