# Generated by Django 5.2 on 2025-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_remove_medioproteccion_seleccionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosemergencia',
            name='plano',
            field=models.FileField(blank=True, null=True, upload_to='emergencias/'),
        ),
        migrations.AlterField(
            model_name='equipoemergencia',
            name='tipo',
            field=models.CharField(choices=[('JEFE', 'Jefe de Emergencia'), ('SUSTITUTO', 'Sustituto Jefe de Emergencia'), ('INTERVENCION', 'Equipo de Intervención'), ('EVACUACION', 'Equipo de Alarma y Evacuación'), ('PRIMEROS AUXILIOS', 'Equipo de Primeros Auxilios')], max_length=30),
        ),
    ]
