# Generated by Django 5.2 on 2025-06-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_documentosemergencia_plano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='doc_tipos/')),
            ],
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('empresa', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=100)),
                ('causas_inmediatas', models.TextField()),
                ('causas_basicas', models.TextField()),
                ('informe', models.FileField(upload_to='investigaciones/')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
