# Generated by Django 5.2 on 2025-07-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_accidente_accioncorrectiva_investigacionaccidente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidente',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='investigacionaccidente',
            name='accidente',
        ),
        migrations.RemoveField(
            model_name='investigacionaccidente',
            name='acciones',
        ),
        migrations.DeleteModel(
            name='DocumentoTipo',
        ),
        migrations.DeleteModel(
            name='Investigacion',
        ),
        migrations.RemoveField(
            model_name='procedimientoinvestigacion',
            name='archivo',
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='codigo',
            field=models.CharField(default='NA-000', help_text='Código único de investigación', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='formato',
            field=models.FileField(blank=True, null=True, upload_to='investigaciones/formularios/'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='informe_pdf',
            field=models.FileField(blank=True, null=True, upload_to='investigaciones/informes/'),
        ),
        migrations.AddField(
            model_name='procedimientoinvestigacion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='investigaciones/procedimientos/'),
        ),
        migrations.AddField(
            model_name='procedimientoinvestigacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empresamedioproteccion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='causas_inmediatas',
            field=models.TextField(blank=True, help_text='Causas inmediatas del accidente', null=True),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='causas_raiz',
            field=models.TextField(blank=True, help_text='Causas raíz del accidente', null=True),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='fecha_investigacion',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Accidente',
        ),
        migrations.DeleteModel(
            name='AccionCorrectiva',
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='acciones',
            field=models.TextField(blank=True, help_text='Acciones correctivas/preventivas', null=True),
        ),
    ]
