# Generated by Django 5.2.3 on 2025-07-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_remove_accidente_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoProteccionIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('riesgos', models.CharField(help_text='Riesgos de los que protege', max_length=255)),
                ('norma_une', models.CharField(help_text='Norma UNE de referencia', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPIPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.puestotrabajo')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.equipoproteccionindividual')),
            ],
            options={
                'unique_together': {('puesto', 'epi')},
            },
        ),
    ]
