# Generated by Django 5.2.3 on 2025-07-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_equipoproteccionindividual_epipuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('riesgos', models.CharField(max_length=200)),
                ('norma', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='puestotrabajo',
            name='epis',
            field=models.ManyToManyField(blank=True, to='gestion.epi'),
        ),
    ]
