# Generated by Django 5.2.3 on 2025-07-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_epi_puestotrabajo_epis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='epis_necesarios',
        ),
    ]
