# Generated by Django 5.2 on 2025-07-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_remove_puestotrabajo_epis_necesarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('titular', 'Empresa Titular'), ('contratista', 'Contratista'), ('subcontrata', 'Subcontrata')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AccesoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=200)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='cae/documentos/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmergenciaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(upload_to='cae/emergencias/')),
                ('empresas', models.ManyToManyField(to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('solucion', models.TextField(blank=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('actividad', models.CharField(max_length=200)),
                ('fecha_designacion', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ReunionCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('acta', models.FileField(blank=True, null=True, upload_to='cae/reuniones/')),
                ('resumen', models.TextField()),
                ('empresas', models.ManyToManyField(to='gestion.empresa')),
            ],
        ),
    ]
